# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d34105396bc741e9e7dfb117cb4cd48726b4791c873bd4819b48cab226c24c20c277f1697719e36a6849fd8dcc0e688089f70783f931abe37c90cf29369f491

test:
  secret_key_base: ed3679169b4fb69bab11dc44e81865cb15eb4bdccfeacc1b3e9f9d2369fa6c1af34570f68e96a6ce1d1d0558275caee34dbe553a23fc5bb5a525c63f05b97131

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
